# Generated by Django 5.1 on 2024-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_a_k', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='administrator',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='images/video/%Y/%m/%d/', verbose_name='Видео'),
        ),
    ]
