# Generated by Django 5.1 on 2024-10-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_a_k', '0002_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%d/', verbose_name='Видео'),
        ),
    ]
